### ISSUE TITLE
remote URL specification of upload document not working

### ISSUE THREAD

**Issue by scott2b** [datadesk/python-documentcloud#103]
Per DocumentCloud API documentation (https://www.documentcloud.org/help/api#upload-documents) for upload: "You can either upload a local file using a standard multi-part upload, or tell DocumentCloud to download the file from a public server by passing a URL." And, in the parameter description for the file parameter: "either the contents of a local file, or the URL where the document can be found".

However, with python-documentcloud the option to pass a URL does not seem to be supported. I am getting the following error:

FileNotFoundError: [Errno 2] No such file or directory: 'http://ord.legistar.com/Chicago/attachments/e3a0cbcb-044d-4ec3-9848-23c5692b1943.pdf'

**Comment by palewire** [comment]
Huh. I didn't even know that was a feature of DocumentCloud. I guess we'd need to sniff that it is an URL and then verify that it works with a HEAD request? Or should we pass it without checking if it works?

**Comment by scott2b** [comment]
Looking a bit at the code for this. I think for backwards compatibility and safety you probably want to assume that the user intends to pass in a file and fall back to treating it like a url. So maybe check to see if the file exists and plow forward if that is the case, otherwise check to see if it parses out as a valid url and pass it in as the file parameter without doing the filesize checks etc.

**Comment by scott2b** [comment]
Hey Ben, I've got a rough first pass at this working that does the following:

 * If the file param doesn't look like a file (ie. doesn't have 'read') check to see if the file exists
 * If the file exists process as before
 * Else: issue a head request on the location of file. If that fails raise an exception otherwise submit the request to document cloud with this string URL as the file parameter.

I did it this way because URL parsing gets a bit hairy between 2, and 3 and so if we want a HEAD request for safety, it seems cleaner just to go ahead and issue the HEAD and leave the notion of URL correctness to be handled by whatever URL library is being used.

On that note, I am using requests at the moment. I see requests is a dependency in requirements.txt, but doesn't seem to be getting used here. However, for some reason I have not yet figured out, the document cloud request is not working with the internal handler (ie. _make_request) whereas I am able to submit the call with the requests library just fine.

Let me know what you think about the above approach, whether you want me to sort out the issue with _make_request (or just use requests) and if you want me to issue a pull request.

Thanks!

**Comment by scott2b** [comment]
Another quick question. While I am in this code, would it make sense to make the document return optional? In my case at least, this seems a bit heavy and somewhat undermines the point of uploading via URL passing. I was thinking about adding a return_document parameter that defaults to True and if set to False then return the document cloud API upload response instead.

**Comment by palewire** [comment]
I'm interested in any patches that make sense to you, though I haven't really thought through what we'd want to merge. I'll take a dip into the code myself a little bit this afternoon and see if I can scratch your itch.

**Comment by palewire** [comment]
I'm also open to refactoring the application to use the much nicer requests library, but we'd need to ensure we have multipart upload support.

**Comment by knowtheory** [comment]
I'd still think you'd want the document to be returned.  If you don't do so you'll have no handle in your local process to represent the object you've just created right?  If you don't need it, presumably you can just discard it.

Adding a flag is interesting, i don't know the norms in python land well enough to know whether folks would expect that

**Comment by scott2b** [comment]
hey Ted, thanks. In this case we're doing processing on the backend of getting documents from a public location into Document Cloud. I actually need the ID, not the binary document, so that I can associate the ID with my own data for the document. With the given code, I'm a bit confused in fact about how one would go about retrieving a document sometime later -- there is nothing here to support that from what I can see. I am guessing then that other people are uploading documents and then just searching for them later rather than retrieving them explicitly.

**Comment by scott2b** [comment]
Actually, I might be confused here. I thought it was returning the binary of the actual uploaded document. If that is not the case, then my suggestion is way off.

**Comment by scott2b** [comment]
Ok, I see now that it is returning a Document object (ie. an instance of the Document class). My bad. Scratch my request for making the document return optional -- I was misinterpreting an error in my code. The current approach of returning a Document instance seems like the right thing to do.

**Comment by palewire** [comment]
Okay I made a patch to the trunk, with a new dependency to detect valid URLs. Give it a try. We'll see what TravisCI has to say shortly.

**Comment by scott2b** [comment]
at first glance: you will want to protect from comparing None with an integer on line 287

**Comment by scott2b** [comment]
This is very similar to what I first tried to do. For some reason the request handler does not like the request. If I pass a URL into this, I get:

...
 File "/Users/scott/env/cityhallmonitor/lib/python3.3/site-packages/python_documentcloud-1.0.1-py3.3.egg/documentcloud/__init__.py", line 80, in _make_request
  File "/usr/local/Cellar/python3/3.3.3/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py", line 467, in open
    req = meth(req)
  File "/usr/local/Cellar/python3/3.3.3/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py", line 1179, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.

**Comment by scott2b** [comment]
To follow up, and to be clear, the above mentioned TypeError on the POST data is the specific issue that led me earlier to getting this working with requests instead of _make_request.

**Comment by palewire** [comment]
Good point. Duh. Silly bug on my part. 

This is now working for me. You?

```python
from documentcloud import DocumentCloud
client = DocumentCloud('ben.welsh@latimes.com', 'mycrazypassword')
url = 'http://ord.legistar.com/Chicago/attachments/e3a0cbcb-044d-4ec3-9848-23c5692b1943.pdf'
obj = client.documents.upload(url)
```

**Comment by scott2b** [comment]
Hm, no. I get the following. Could this maybe be a Python 2 vs. 3 thing?:

```
>>> obj = client.documents.upload(url)
Retrying in 2 seconds
Retrying in 4 seconds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/scott/env/cityhallmonitor/lib/python3.3/site-packages/python_documentcloud-1.0.1-py3.3.egg/documentcloud/toolbox.py", line 53, in _checkcredentials
  File "/Users/scott/env/cityhallmonitor/lib/python3.3/site-packages/python_documentcloud-1.0.1-py3.3.egg/documentcloud/__init__.py", line 322, in upload
  File "/Users/scott/env/cityhallmonitor/lib/python3.3/site-packages/python_documentcloud-1.0.1-py3.3.egg/documentcloud/toolbox.py", line 83, in f_retry
  File "/Users/scott/env/cityhallmonitor/lib/python3.3/site-packages/python_documentcloud-1.0.1-py3.3.egg/documentcloud/__init__.py", line 90, in _make_request
  File "/Users/scott/env/cityhallmonitor/lib/python3.3/site-packages/python_documentcloud-1.0.1-py3.3.egg/documentcloud/__init__.py", line 80, in _make_request
  File "/usr/local/Cellar/python3/3.3.3/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py", line 467, in open
    req = meth(req)
  File "/usr/local/Cellar/python3/3.3.3/Frameworks/Python.framework/Versions/3.3/lib/python3.3/urllib/request.py", line 1179, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
```

**Comment by palewire** [comment]
Ah. Got it. We'll we're halfway there.

**Comment by palewire** [comment]
I wonder if we need to encode it to bytes somewhere, and then maybe even do some other dancing further down the pipes when we get in the multipart request handler.

**Comment by scott2b** [comment]
Man, I don't know -- there's a lot going on in the request handler ... but is there really a need for the multipart handler in the case where we are passing a URL instead of a file?

**Comment by palewire** [comment]
Good point!

**Comment by palewire** [comment]
Okay, @scott2b. Sorry for the delay. I pushed a fresh patch and it *appears* to be working for me in both Python 2 and 3. Give it a try.

**Comment by scott2b** [comment]
This looks like it is working. Thanks so much Ben -- this is going to be really useful for us.

**Comment by palewire** [comment]
Great. I'll ship a new version to PyPI today with this addition.

**Comment by palewire** [comment]
Version 1.0.2 just shipped to PyPI with this add. Try upgrading with pip and see how it goes. Good luck!

**Comment by scott2b** [comment]
Yep it's working. Thank you!

**Comment by palewire** [comment]
![ups](http://i.imgur.com/guj5Fl4.gif)
