### ISSUE TITLE
Plus symbols get lost in document data

### ISSUE THREAD

**Issue by scott2b** [datadesk/python-documentcloud#105]
I am guessing this is an escaping issue having to do with a plus (+) symbol getting treated as a space in the request to DocumentCloud.

You can replicate this with any document object doc:
```
>>> doc.data = {'testkey': 'foo+bar'}
>>> doc.put()
>>> doc.id
>>> modified = client.documents.get(doc.id)
>>> modified.data
{'testkey': 'foo bar'}
```
In our case, this issue is particularly relevant to dates with timezones, which have a + in the formatting.

**Comment by palewire** [comment]
This is something I'd never considered. @knowtheory, could this be on your end?

**Comment by knowtheory** [comment]
Looks like data params aren't being uri encoded: https://github.com/datadesk/python-documentcloud/blob/master/documentcloud/__init__.py#L121-L124

**Comment by palewire** [comment]
Thanks! I'll set up a test for this and then fix it.

**Comment by knowtheory** [comment]
:heart:

**Comment by palewire** [comment]
Alright, @scott2b. I *think* I fixed this and pushed a new release to PyPI. Give it a shot and let me know if you're still having problems. Thanks for the help, @knowtheory.

**Comment by scott2b** [comment]
Yep, working. Thank you!!!

**Comment by palewire** [comment]
Thanks for the bug report. Stuff like this is how we keep improving.
