### ISSUE TITLE
data keys & values are expected to be strings

### ISSUE THREAD

**Issue by scott2b** [datadesk/python-documentcloud#106]
I'm not sure if this is a bug or intended behavior, but due to the recent change, I think this might break some existing code in the wild. Re: https://github.com/datadesk/python-documentcloud/blob/master/documentcloud/__init__.py#L121-L126

The call to encode assumes the user has passed in a string. This will not work, for instance, if an integer is passed in. I am fine with casting my data to strings on my end -- just wanted to point this out because the behavior is different as a result of the recent fix to deal with + signs.

**Comment by palewire** [comment]
well, that's a good point. I don't know if DocumentCloud supports saving integers and other data types. If they ultimately force everything to string, maybe we should too.

**Comment by knowtheory** [comment]
Yep that's right, right now, everything that goes into document data is assumed to be a string.

The plan is to start using jsonb postgres type to store document data... but i suspect we're going to probably continue to coerce everything into strings.  I'm not super excited about the prospect of being an arbitrary dumb datastore.

**Comment by scott2b** [comment]
Right, this does not really affect DocumentCloud behavior. The behavior change is just in the python library. Where before, non-string values would be coerced into strings, now non-strings will throw an exception. So yes, it's something of a judgement call on what you want the API to be -- expect users to pass in strings, or coerce whatever they pass in into strings. My main point is that the recent code change will break code out there that is still expecting the coercive behavior to still work.

**Comment by palewire** [comment]
Yeah, if DocCloud forces to a string I don't see the harm in us doing it. Got any opinions on the best Python route for doing that?

**Comment by scott2b** [comment]
While just calling str() on the value should work in general, I am inclined to think that you might want to call unicode() in the case of Python 2.



—

**Comment by palewire** [comment]
I'm looking at this now and here's the traceback I receive when I submit an integer as a data key. Submitted mostly for the record.

```python
Traceback (most recent call last):
  File "scratch.py", line 14, in <module>
    doc.put()
  File "/home/ben/Code/python-documentcloud/documentcloud/__init__.py", line 641, in put
    self._connection.put('documents/%s.json' % self.id, params)
  File "/home/ben/Code/python-documentcloud/documentcloud/toolbox.py", line 53, in _checkcredentials
    return method_func(self, *args, **kwargs)
  File "/home/ben/Code/python-documentcloud/documentcloud/__init__.py", line 126, in put
    list(data.items())
AttributeError: 'int' object has no attribute 'encode'
```

**Comment by palewire** [comment]
Here's where I get lost in unicode land. The key lines of code seem to come when the data attributes are appended to the URL [here](https://github.com/datadesk/python-documentcloud/blob/master/documentcloud/__init__.py#L121-L127)

```python
            params += "".join([
                '&data[%s]=%s' % (
                    urllib.parse.quote_plus(key.encode("utf-8")),
                    urllib.parse.quote_plus(value.encode("utf-8"))
                ) for key, value in
                list(data.items())
            ])
```

Now, if I start wrapping the key and value items in ``str`` it will fix the integers, but it will start crashing if unicode strings containing Chinese symbols and other non-latin characters are included.

**Comment by palewire** [comment]
I just pushed a hacky patch that runs a loop through the data dict before passing it up to save at DocumentCloud that sanitizes the values. It's [right here](https://github.com/datadesk/python-documentcloud/commit/0f71f0e23bfc41bb35bce2a8ac287fd40710a868).

Seems pretty kludgy to be though. Part of me things a stricter, more professional bit of Python would be enforcing the data type rules on the dictionary itself when it is edited and accessed. But that seems like it would require some dictionary subclassing or something that might a good bit of trouble. 

Though perhaps I could just simply throw an error if a non-string is added as a key or value. I might experiment with that next.

**Comment by palewire** [comment]
The patch just above this one does validate keys and values of new data dictionaries if they are edited in this style.

```python
obj.data = {1: 234}
```

And as I reflect on this problem I think I prefer this solution because it avoids "magic" and goes with the old Python saw "explict is better than implicit." However, the solution does not solve for the very common case where a key or value is edited on an already existing dictionary like this:

```python
obj.data['key'] = 1
```

So the solution is incomplete until I can work that out.

**Comment by palewire** [comment]
Alright, this hilarious argument with myself has now resulted in me totally flip flopping. In the last commit I went ahead and wrong a custom dictionary override that I think will both prevent integers and other non-strings from being set but also enforce DocumentCloud's reserved keywords as well. Take a look and [point out what sucks](https://github.com/datadesk/python-documentcloud/commit/b2b5892086d0dead8efa1aef39dc202bf4928c9d).

**Comment by palewire** [comment]
The tests just passed so unless anyone objects I am going to call this ticket closed.
