### ISSUE TITLE
Support search.json 'page' parameter in search method

### ISSUE THREAD

**Issue by jywsn** [datadesk/python-documentcloud#107]
Possibly related to #97 and #98 

The search.json API method accepts the additional parameters listed here: https://www.documentcloud.org/help/api  Of particular interest to me is the `page` parameter.

Executing a query to return all documents in our particular DocumentCloud project eventually locks up our server, and the speculation is that the mass creation of 66K+ Document objects is causing the problem.  

Our initial inclination was to break up the single, massive query into multiple, smaller queries using the `page` parameter, but the `search` method does not support that (and the `page` parameter is used internally within the `_get_search_page` function).

**Comment by palewire** [comment]
A good idea. The [existing search code](https://github.com/datadesk/python-documentcloud/blob/master/documentcloud/__init__.py#L192-L230) is pretty stoopid simple, looping through all the pages until they are exhausted. 

I can imagine a couple ways of improving that. We could have it skip the loop if a specific page is provided, or we could kill the loop entirely. What do you think?

**Comment by jywsn** [comment]
My current workaround is to call `_get_search_page` directly, basically doing what is inside that while-loop along with the `obj_list` creation.  So I'd just just skip the loop if the caller passes in a `page`

**Comment by palewire** [comment]
I think that makes sense. I doubt it's a huge patch, though I don't know if I can get to it today.

**Comment by palewire** [comment]
I believe these changes are now in the master trunk and set for the next release. You can provide a page number and a per_page value to pick whatever you'd like (if I got it right). [Docs](http://python-documentcloud.readthedocs.org/en/latest/documents.html#client.documents.search)
