### ISSUE TITLE
issues with pulling OCR'd text

### ISSUE THREAD

**Issue by ryanvmenezes** [datadesk/python-documentcloud#108]
I keep getting the same error when I try the `full_text` property on a document:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/documentcloud/__init__.py", line 766, in get_full_text
    return self._get_url(self.full_text_url)
  File "/usr/local/lib/python2.7/dist-packages/documentcloud/__init__.py", line 743, in _get_url
    return urllib.request.urlopen(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
```

All the other properties seem to be accessible. Not sure what this error is saying.

**Comment by ryanvmenezes** [comment]
Both of the for-loops at the bottom fail and produce the above traceback:

```python
from documentcloud import DocumentCloud

client = DocumentCloud('ryan.menezes@latimes.com', pwd)

project, created = client.projects.get_or_create_by_title(project_title)

for i in project.document_ids:
    obj = client.documents.get(id=i)
    print obj.full_text

for i in project.document_list:
    print i.full_text
```

**Comment by ryanvmenezes** [comment]
Other properties, such as `entities` and `pages` work in both cases.

**Comment by knowtheory** [comment]
Hmm.  we have been upgrading everything to SSL primarily... Although i don't know enough about Python's default SSL handling in various sundry URL libraries to know... Maybe @palewire can help supply some of that info?

**Comment by palewire** [comment]
Python's SSL is all fucked in new 2.X versions. @ryanvmenezes run this and tell me what it says:

```bash
$ python -V
```

**Comment by ryanvmenezes** [comment]
I'm running 2.7.6

**Comment by palewire** [comment]
A little testing verifies that the SSL is the source of the bug. So I think for at least a temporary fix I am going to strip the ``https`` from the URLs and request the vanilla ``http``. Of course I would like to be have the SSL working but I'd rather ship a bugfix version that works in the mean time.

**Comment by palewire** [comment]
Alright I think I have deployed a bugfix edition to the Python Package Index that simply drops SSL from those URLs. Upgrade like so and try your full text pull again.

```python
$ pip install python-documentcloud --upgrade
```

**Comment by ryanvmenezes** [comment]
this worked. thanks
