### ISSUE TITLE
Support search.json 'data' parameter in search method

### ISSUE THREAD

**Issue by jywsn** [datadesk/python-documentcloud#109]
Related to #107 

It would be great if the search method supported the `data` parameter.  We have a use case in which we are always accessing the key/value data for the documents in our search results.  We have over 60K+ documents, so this results in a lot of calls to `_lazy_load` the metadata.  

It absolutely makes sense for "no data" to be the default (as it is in the JSON API), but being able to set `data=true` would save us a lot of extra network calls.

**Comment by palewire** [comment]
I believe these changes are now in the master trunk and set for the next release. [Docs](http://python-documentcloud.readthedocs.org/en/latest/documents.html#client.documents.search)
