### ISSUE TITLE
Unittest for the "force_ocr" option

### ISSUE THREAD

**Issue by palewire** [datadesk/python-documentcloud#112]
I wonder if there's somehow we can test whether the feature added by #110 is working.

**Comment by anthonydb** [comment]
Thinking about it, how about:

* Upload the same document twice, once with `force_ocr` enabled.
* Each time, retrieve the text.
* Compare whether the text is identical? If not, then OCR occurred.

That may at least demonstrate that the document was processed differently.

**Comment by knowtheory** [comment]
Force OCR is a directive essentially and not really a thing that's going to be directly testable on your end.

One of the reasons i'm a little uncomfortable exposing :force_ocr is that it edges towards revealing an entire queueing systems worth of domain objects to provide verification of various settings and options via ReST.

The conceptual set up for DocumentCloud broadly speaking is that it's a system that describes a bunch of documents, notes and so on.  Allowing people to specify and retrieve confirmation of options like _how_ a document got into it's current state require reifying all the procedures that result in that document's state.

So, i'm trying to avoid that right now.

My question to you is... what do you actually want to unit-test with this option?  Do i need to provide a sidecar back that specifies processing options?

**Comment by palewire** [comment]
Pass
