### ISSUE TITLE
Clarify that the project argument to client.documents.upload and client.documents.upload_directory is the project ID

### ISSUE THREAD

**Issue by ghing** [datadesk/python-documentcloud#120]
From the [API documentation](https://python-documentcloud.readthedocs.io/en/latest/documents.html#uploading), it's not clear that `project` is the project ID. Since there's a `Project` class, I originally thought this was the type expected for this argument. As seen in #80, others have been confused about whether this argument is the project ID or title.

If there's a style of documenting argument types/meaning that you like, I'm happy to submit a pull request.

**Comment by palewire** [comment]
This is a good point. TBH, the whole project handling bit of this library could use some work.

**Comment by palewire** [comment]
> This repository has been deprecated. A newer version, adapted to fit DocumentCloud's latest API, is now maintained at [github.com/MuckRock/python-documentcloud/](https://github.com/MuckRock/python-documentcloud/). Due to changes in how DocumentCloud works, the code here will no longer work. You should upgrade to version 2.0 or higher.
