### ISSUE TITLE
In need of `force_ocr` and next release date

### ISSUE THREAD

**Issue by catriuspham** [datadesk/python-documentcloud#124]
I realize that `force_ocr` was added in https://github.com/datadesk/python-documentcloud/commit/393bbcf51aaf0f81abde594b2b0b51a495167b4a#diff-22ac016e621bf93a48776ba682ff652f on Jan 28, 2016. But the latest version 1.0.4 was released on Nov 22, 2015, nearly 3 years ago. 
So:
- In the latest version 1.0.4, when a document be uploaded to DocumentCould, will it run through the OCR process?
- Do you have any plan for the next release?

**Comment by palewire** [comment]
Embarassing, I know! 

I have a few bugs to fix before the next release. I am out of town on a family trip currently. Is late next week too late for you?

**Comment by palewire** [comment]
Done!
