### ISSUE TITLE
Reprocess text

### ISSUE THREAD

**Issue by catriuspham** [datadesk/python-documentcloud#126]
We can reprocess OCR text in the UI.

 - Double-click the document to open it in the document workspace.
- In the sidebar, click "Reprocess Text." In the dialog, click "Force OCR."

They used a POST to https://www.documentcloud.org/documents/[document_id]/reprocess_text with `ocr: true`.
Do we have it in `python-documentcloud`?

**Comment by palewire** [comment]
I don't know! @knowtheory, can we do it?

**Comment by palewire** [comment]
> This repository has been deprecated. A newer version, adapted to fit DocumentCloud's latest API, is now maintained at [github.com/MuckRock/python-documentcloud/](https://github.com/MuckRock/python-documentcloud/). Due to changes in how DocumentCloud works, the code here will no longer work. You should upgrade to version 2.0 or higher.
