### ISSUE TITLE
Would it be desirable to add a method for updating individual values for document data?

### ISSUE THREAD

**Issue by meli-lewis** [datadesk/python-documentcloud#127]
I admit I ask because I kept absentmindedly trying to update with `doc.data['key'] = 'value'` rather than `doc.data = {'key': 'value'}` today. I could see it being advantageous to leave behavior as it is, because what I tried opens at least one can of testing worms, but I figured it best to check!

Thanks again for the incredibly useful tools, y'all.

**Comment by palewire** [comment]
Sure. Always happy to consider a thoughtful patch.

**Comment by palewire** [comment]
> This repository has been deprecated. A newer version, adapted to fit DocumentCloud's latest API, is now maintained at [github.com/MuckRock/python-documentcloud/](https://github.com/MuckRock/python-documentcloud/). Due to changes in how DocumentCloud works, the code here will no longer work. You should upgrade to version 2.0 or higher.
