### ISSUE TITLE
does the 'project' kwarg work on upload and upload directory? I'm cornfused

### ISSUE THREAD

**Issue by palewire** [datadesk/python-documentcloud#80]

**Comment by jywsn** [comment]
It definitely works on `DocumentClient.upload`.  I haven't used `upload_directory`, but that method uses `upload`, so it should work.

**Comment by siccovansas** [comment]
There is some inconsistency with `client.documents.upload` and the `project` argument. When uploading a PDF file from your computer you can only use a `string` in the `project` argument, but when you link to a PDF URL it accepts both a `string` and an `integer`. It took me some time to understand why uploading did not work anymore when I switched from using URLs to local files, so fixing this might avoid some frustration for others :D

**Comment by palewire** [comment]
Sorry for this confusion. I'll take a look at it. Though could you please clarify what you mean when you say "link to a PDF url."

**Comment by siccovansas** [comment]
Thanks!
To clarify, see https://python-documentcloud.readthedocs.org/en/latest/documents.html#uploading
It says: You can also URLs link to PDFs, if that’s the kind of thing you want to do.
`client.documents.upload("http://ord.legistar.com/Chicago/attachments/e3a0cbcb-044d-4ec3-9848-23c5692b1943.pdf")`

**Comment by palewire** [comment]
Weird. Now that's something I hadn't considered. 

Regardless of how you submit a document, the project keyword argument is passed along in the same format by [this bit of code](https://github.com/datadesk/python-documentcloud/blob/master/documentcloud/__init__.py#L345-L346).

The one differnece I see that is URL uploads do not use a "multipart" post handler to pass along all that PDF data. Though I'm not sure that should make much difference.

Can you provide some examples of the code you're running that's not working? Are there error messages?

**Comment by cjwinchester** [comment]
I've been running into an ish when I tried to upload to a specific project. Here's the function I'm calling:

```
from documentcloud import DocumentCloud
import os


def dc_upload_handler(fileobj, title, description, proj_name, access_level):
    dc_username = os.environ['DC_USERNAME']
    dc_password = os.environ['DC_PASSWORD']
    client = DocumentCloud(dc_username, dc_password)
    obj = client.documents.upload(
        fileobj,
        title=title,
        description=description,
        project=proj_name,
        access=access_level
    )
    return client.documents.get(obj.id)
```

I'm not getting any errors, and the document uploads fine -- it's just not attached to the project I specified. I've confirmed that the string I'm passing for the project matches the name of the project on DC. I also tried fetching the project first -- `client.projects.get_by_title(proj_name)` -- and then passing that as the parameter to the upload function, but no dice.

**Comment by palewire** [comment]
What are you passing in as the ``proj_name`` variable?

**Comment by cjwinchester** [comment]
The project name as a string. E.g.: `dc_upload_handler("test.pf", "Title", "Description of PDF", "Project Name", "public")`

**Comment by palewire** [comment]
[According to the official API documentation](https://www.documentcloud.org/help/api#upload-documents), DocumentCloud expected the "number Project id" for that input. Try that and see if that works.

**Comment by cjwinchester** [comment]
Bingo. Thanks.

**Comment by palewire** [comment]
This is something we should spell out more clearly in the documentation. I'm curious where you looked that failed to make this need clear.

**Comment by cjwinchester** [comment]
[Documents >> uploading](https://python-documentcloud.readthedocs.org/en/latest/documents.html#uploading). My though process was: if you can [fetch](https://python-documentcloud.readthedocs.org/en/latest/projects.html#retrieval) a project by either its ID or title, maybe you could also post to one in the same way. (I might add a few lines to my function to fetch the project by name and return the ID.)

**Comment by palewire** [comment]
yeah that's a pretty reasonable thing to thing. I wonder if we should be testing if an object is submitted, and if so pulling the ID.

**Comment by palewire** [comment]
> This repository has been deprecated. A newer version, adapted to fit DocumentCloud's latest API, is now maintained at [github.com/MuckRock/python-documentcloud/](https://github.com/MuckRock/python-documentcloud/). Due to changes in how DocumentCloud works, the code here will no longer work. You should upgrade to version 2.0 or higher.
