### ISSUE TITLE
Give an offset and limit, as with sql alchemy

### ISSUE THREAD

**Issue by AbeHandler** [datadesk/python-documentcloud#98]
Hello, 

I'm using this library and need to do offsets and limits, like you can do with SQL alchemy. 

For instance, I want to do something like
     client.search("Ruben Salazar", 10, 100)  #to pull documents 100 through 110 

Is that something others would want? It seems fairly simply to modify the code to get there.

**Comment by palewire** [comment]
I believe these changes are now in the master trunk and set for the next release. You can provide a page number and a per_page value to pick whatever you'd like (if I got it right). [Docs](http://python-documentcloud.readthedocs.org/en/latest/documents.html#client.documents.search)
