### ISSUE TITLE
Sniff PDF file size prior to upload to make sure it isn't over the API's 400MB limit

### ISSUE THREAD

**Issue by palewire** [datadesk/python-documentcloud#99]
If you try to upload a file over 400MB, [DocumentCloud will throw an error](https://github.com/documentcloud/documentcloud/blob/master/config/server/files/nginx/nginx.conf#L22). 

So we should just raise a Python exception [here](https://github.com/datadesk/python-documentcloud/blob/master/documentcloud/__init__.py#L263) rather than let you wait for it to post and be disappointed when it fails.

**Comment by anthonyjpesce** [comment]
Working flawlessly so far, thank you!
